# Generated by Django 2.1.5 on 2019-02-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[(1, 'NEW'), (2, 'PENDING'), (3, 'COMPLETED'), (4, 'ERROR')], default=1, max_length=255)),
                ('response_length', models.PositiveSmallIntegerField(default=0, verbose_name='Response content length')),
                ('response_status', models.PositiveSmallIntegerField(default=0, verbose_name='Response content status')),
                ('response_body', models.TextField(default='', verbose_name='Response content body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
